name: Bump Version and Create PR

on:
  workflow_dispatch:
    inputs:
      versionIncrement:
        type: choice
        description: Version Increment
        options:
          - patch
          - minor
          - major
jobs:
  bump-version:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run
        run: |
          git config --local user.email "dev+${{ github.actor }}@irwinsolutions.com"
          git config --local user.name "${{ github.actor }}"          

          # Override the default npm version to commit the package.json version bump (as we want it on a different branch)
          npm version ${{ github.event.inputs.versionIncrement }} --git-tag-version false

          # Grab the "new" version from the pcakage.json
          version=$(cat package.json | jq -r '.version')
          echo "Set version: $version"

          # Create the new branch
          branchName="version/$version"
          echo "Creating a branch: $branchName"          
          git checkout -b "$branchName"

          # Push the changes
          git add .
          git commit -m "deploy: $version"
          git push -u origin "$branchName"

          # Create a PR request
          gh pr create -B dev -H $branchName --title 'Deploy $version' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
